baseURL = "https://oedph.netlify.app"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Educcentral Philippines Online Education"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "tools"
name = "tools"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Educcentral Philippines"
contact_form_action = "#"
copyright = "&copy; 2020 [EduccentralPH](https://educcentralph.ml) All Rights Reserved"
description = "Educcentral Philippines"
google_analitycs_id = ""
google_tag_manager = "Educcentral Philippines"
home = "Home"
logo = "images/shield.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi. Welcome to Educcentral Philippines. <br> <p>Together, let us bring Education for All.</p>"
[params.cta]
description = "Support us in our mission and goals!"
enable = true
image = "images/hugo-muscot.svg"
title = "Visit our site"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://educcentralph.ml/shop"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
